# docker-compose.yml
version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.development
      # args:
      #   - UNSPLASH_ACCESS_KEY
      #   - UNSPLASH_SECRET_KEY
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    env_file: ./src/.env-unsplash
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
      - APACHE_RUN_USER=apache-www-volume
      - APACHE_RUN_GROUP=apache-www-volume
      # - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
      # - UNSPLASH_SECRET_KEY=${UNSPLASH_SECRET_KEY}
